## 20260321_nuc118_pca.R
## PCA from PCAngsd covariance matrix (118 nuclear samples, minInd=24)
## Coverage artifact check, colored by bloom status, cruise, and year
## Run locally in RStudio
##
## INPUT FILES (all in working directory):
##   nuc118_pcangsd_minInd24.cov    -- PCAngsd covariance matrix (v2, 500 iter)
##   nuc120_flagstat_summary.tsv    -- per-sample mapped read counts
##
## The covariance matrix rows are in BAM list order. We reconstruct sample
## metadata from the flagstat summary, which has the same ordering as the
## BAM list (it was generated by iterating through the BAM list).

## ---- Read covariance matrix ----
cov_mat <- as.matrix(read.table("nuc118_pcangsd_minInd24.cov"))
cat("Covariance matrix dimensions:", nrow(cov_mat), "x", ncol(cov_mat), "\n")

## ---- Read flagstat summary for sample names and mapped reads ----
## The flagstat file has BAM paths and mapped read counts
## Format assumed: tab-delimited, columns include BAM path and mapped reads
flagstat <- read.delim("nuc120_flagstat_summary.tsv", header = TRUE,
                       stringsAsFactors = FALSE)
cat("Flagstat rows:", nrow(flagstat), "\n")
cat("Flagstat columns:", paste(names(flagstat), collapse = ", "), "\n")

## Extract sample names from BAM paths
## BAM names are like DD_4_23.opg.markdup.bam or EG9.ds.opg.markdup.bam
## We need the sample ID portion
extract_sample_id <- function(bam_path) {
    fname <- basename(bam_path)
    ## Remove suffixes: .ds.opg.markdup.bam or .opg.markdup.bam
    id <- sub("\\.ds\\.opg\\.markdup\\.bam$", "", fname)
    id <- sub("\\.opg\\.markdup\\.bam$", "", id)
    return(id)
}

## Try to find the BAM path column
bam_col <- grep("bam|path|file", names(flagstat), ignore.case = TRUE, value = TRUE)
mapped_col <- grep("mapped|reads", names(flagstat), ignore.case = TRUE, value = TRUE)

cat("\nDetected BAM column:", bam_col, "\n")
cat("Detected mapped reads column:", mapped_col, "\n")

## If column detection fails, print the first few rows and stop
if (length(bam_col) == 0 || length(mapped_col) == 0) {
    cat("\nWARNING: Could not auto-detect columns. Here are the first 3 rows:\n")
    print(head(flagstat, 3))
    cat("\nPlease edit the script to set bam_col and mapped_col manually.\n")
    ## Fallback: assume first column is BAM, second is mapped reads
    bam_col <- names(flagstat)[1]
    mapped_col <- names(flagstat)[2]
    cat("Falling back to:", bam_col, "and", mapped_col, "\n")
}

sample_ids <- sapply(flagstat[[bam_col[1]]], extract_sample_id)
mapped_reads <- as.numeric(flagstat[[mapped_col[1]]])
names(mapped_reads) <- sample_ids

cat("\nSamples:", length(sample_ids), "\n")
cat("First 5 sample IDs:", paste(head(sample_ids, 5), collapse = ", "), "\n")

## Verify dimensions match
stopifnot(length(sample_ids) == nrow(cov_mat))

## ---- Assign cruise from sample ID ----
get_cruise <- function(id) {
    if (grepl("^DM18_", id)) return("DM18")
    if (grepl("^DL5_", id)) return("DL5")
    if (grepl("^DD_", id)) {
        parts <- strsplit(id, "_")[[1]]
        return(paste0("DD", parts[2]))
    }
    ## EG samples mapped to their real IDs should already be DD_ or DM18_ format
    ## If we see EG-prefixed names, handle them
    if (grepl("^EG", id)) return("EG_unknown")
    return(NA)
}

cruises <- sapply(sample_ids, get_cruise, USE.NAMES = FALSE)

## ---- Assign bloom status ----
bloom_cruises <- c("DD7", "DD11", "DD17", "DD21", "DM18")
bloom_status <- ifelse(cruises %in% bloom_cruises, "bloom", "non-bloom")

## ---- Assign year ----
get_year <- function(cruise) {
    if (cruise == "DM18") return("2022")
    if (cruise == "DL5") return("2024")
    if (grepl("^DD", cruise)) {
        dd_num <- as.numeric(gsub("DD", "", cruise))
        if (!is.na(dd_num)) {
            if (dd_num <= 15) return("2016")
            if (dd_num <= 21) return("2017")
        }
    }
    return(NA)
}

years <- sapply(cruises, get_year, USE.NAMES = FALSE)

## Build metadata data frame
meta <- data.frame(
    sample_id = sample_ids,
    cruise = cruises,
    bloom = bloom_status,
    year = years,
    mapped_reads = mapped_reads,
    stringsAsFactors = FALSE
)

cat("\nSamples by bloom status:\n")
print(table(meta$bloom))
cat("\nSamples by cruise:\n")
print(table(meta$cruise))
cat("\nSamples by year:\n")
print(table(meta$year))

## ---- Eigendecomposition ----
eig <- eigen(cov_mat, symmetric = TRUE)
vals <- eig$values
vecs <- eig$vectors

## Percent variance explained
pct_var <- vals / sum(vals) * 100
cat("\nVariance explained by first 10 PCs:\n")
for (i in 1:min(10, length(pct_var))) {
    cat(sprintf("  PC%d: %.2f%%\n", i, pct_var[i]))
}

## ---- Coverage artifact check ----
## Correlate each of the first 5 PCs with log mapped reads
cat("\nCoverage artifact check (Pearson r, PC vs log10 mapped reads):\n")
log_reads <- log10(meta$mapped_reads)
for (i in 1:min(5, ncol(vecs))) {
    r <- cor(vecs[, i], log_reads, use = "complete.obs")
    cat(sprintf("  PC%d vs log10(reads): r = %.3f\n", i, r))
}

## ---- Define color palettes ----
## Bloom colors
bloom_cols <- c("bloom" = "#E41A1C", "non-bloom" = "#377EB8")

## Cruise colors - enough for all cruises
cruise_names <- sort(unique(meta$cruise))
cruise_palette <- c(
    "DD4" = "#1b9e77", "DD6" = "#d95f02", "DD7" = "#7570b3",
    "DD8" = "#e7298a", "DD9" = "#66a61e", "DD10" = "#e6ab02",
    "DD11" = "#a6761d", "DD15" = "#666666", "DD17" = "#1f78b4",
    "DD19" = "#b2df8a", "DD21" = "#fb9a99", "DL5" = "#cab2d6",
    "DM18" = "#ff7f00"
)
## Fill any missing cruises
for (cr in cruise_names) {
    if (!(cr %in% names(cruise_palette))) {
        cruise_palette[cr] <- "#999999"
    }
}

## Year colors
year_cols <- c("2016" = "#4DAF4A", "2017" = "#984EA3",
               "2022" = "#FF7F00", "2024" = "#A65628")

## ---- Plot 1: PCA by bloom status ----
png("20260321_pca_bloom.png", width = 7, height = 6, units = "in", res = 300)
par(mar = c(5, 5, 3, 2))
plot(vecs[, 1], vecs[, 2],
     col = bloom_cols[meta$bloom],
     pch = 19, cex = 1.2,
     xlab = sprintf("PC1 (%.1f%%)", pct_var[1]),
     ylab = sprintf("PC2 (%.1f%%)", pct_var[2]),
     main = "Nuclear PCA (118 samples) - Bloom Status")
legend("topright", legend = names(bloom_cols), col = bloom_cols,
       pch = 19, pt.cex = 1.2, bty = "n")
dev.off()
cat("\nSaved: 20260321_pca_bloom.png\n")

## ---- Plot 2: PCA by cruise ----
png("20260321_pca_cruise.png", width = 8, height = 6, units = "in", res = 300)
par(mar = c(5, 5, 3, 8), xpd = TRUE)
plot(vecs[, 1], vecs[, 2],
     col = cruise_palette[meta$cruise],
     pch = 19, cex = 1.0,
     xlab = sprintf("PC1 (%.1f%%)", pct_var[1]),
     ylab = sprintf("PC2 (%.1f%%)", pct_var[2]),
     main = "Nuclear PCA (118 samples) - Cruise")
legend("topright", inset = c(-0.22, 0),
       legend = cruise_names,
       col = cruise_palette[cruise_names],
       pch = 19, pt.cex = 1.0, bty = "n", cex = 0.75)
dev.off()
cat("Saved: 20260321_pca_cruise.png\n")

## ---- Plot 3: PCA by year ----
png("20260321_pca_year.png", width = 7, height = 6, units = "in", res = 300)
par(mar = c(5, 5, 3, 2))
plot(vecs[, 1], vecs[, 2],
     col = year_cols[meta$year],
     pch = 19, cex = 1.2,
     xlab = sprintf("PC1 (%.1f%%)", pct_var[1]),
     ylab = sprintf("PC2 (%.1f%%)", pct_var[2]),
     main = "Nuclear PCA (118 samples) - Year")
legend("topright", legend = names(year_cols), col = year_cols,
       pch = 19, pt.cex = 1.2, bty = "n")
dev.off()
cat("Saved: 20260321_pca_year.png\n")

## ---- Plot 4: Coverage artifact check ----
png("20260321_pca_coverage_check.png", width = 10, height = 5, units = "in", res = 300)
par(mfrow = c(1, 2), mar = c(5, 5, 3, 2))

r1 <- cor(vecs[, 1], log_reads, use = "complete.obs")
plot(log_reads, vecs[, 1],
     pch = 19, cex = 0.8,
     col = bloom_cols[meta$bloom],
     xlab = "log10(mapped reads)",
     ylab = "PC1 score",
     main = sprintf("PC1 vs Coverage (r = %.3f)", r1))
abline(lm(vecs[, 1] ~ log_reads), lty = 2, col = "gray40")

r2 <- cor(vecs[, 2], log_reads, use = "complete.obs")
plot(log_reads, vecs[, 2],
     pch = 19, cex = 0.8,
     col = bloom_cols[meta$bloom],
     xlab = "log10(mapped reads)",
     ylab = "PC2 score",
     main = sprintf("PC2 vs Coverage (r = %.3f)", r2))
abline(lm(vecs[, 2] ~ log_reads), lty = 2, col = "gray40")
dev.off()
cat("Saved: 20260321_pca_coverage_check.png\n")

## ---- Plot 5: Scree plot (eigenvalues) ----
png("20260321_pca_eigenvalues.png", width = 7, height = 5, units = "in", res = 300)
par(mar = c(5, 5, 3, 2))
n_show <- min(20, length(pct_var))
barplot(pct_var[1:n_show],
        names.arg = 1:n_show,
        xlab = "Principal Component",
        ylab = "% Variance Explained",
        main = "Nuclear PCA Scree Plot (118 samples)",
        col = "steelblue", border = NA)
dev.off()
cat("Saved: 20260321_pca_eigenvalues.png\n")

## ---- Flag DM18_27 on PCA ----
dm18_27_idx <- which(meta$sample_id == "DM18_27")
if (length(dm18_27_idx) == 1) {
    cat("\nDM18_27 position on PCA:\n")
    cat(sprintf("  PC1 = %.4f, PC2 = %.4f\n", vecs[dm18_27_idx, 1], vecs[dm18_27_idx, 2]))
    cat("  (Divergent lineage - check if it is an outlier on PC1 or PC2)\n")
}

## ---- Summary ----
cat("\n===== PCA SUMMARY =====\n")
cat(sprintf("Samples: %d\n", nrow(cov_mat)))
cat(sprintf("SNPs used by PCAngsd: 67,091 (minInd=24, minMaf=0.05)\n"))
cat(sprintf("Significant PCs (MAP test): 1\n"))
cat(sprintf("PC1: %.2f%% variance\n", pct_var[1]))
cat(sprintf("PC2: %.2f%% variance\n", pct_var[2]))
cat(sprintf("PC1 vs log10(reads) r = %.3f\n", cor(vecs[, 1], log_reads, use = "complete.obs")))
cat(sprintf("PC2 vs log10(reads) r = %.3f\n", cor(vecs[, 2], log_reads, use = "complete.obs")))
cat(sprintf("PCAngsd convergence: did not converge (500 iter, RMSE=5.5e-05)\n"))
